/*
* Class to handle Sing up
* Adriano Alves
* Jul 08 2019
*
* */
import 'package:flutter/material.dart';
import 'package:thepetinder/widgets/email.dart';
import 'package:thepetinder/widgets/passwordField.dart';

class SingUp extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => new SingUpState();

}

///  LoginState
class SingUpState  extends State<SingUp>{
  /// ************ Build method ************ \\\
  @override
  Widget build(BuildContext context) {
    /// Scaffold
    return Scaffold(
      /// ********* App Bar ********* \\\
      appBar: AppBar(
        /// Leading Icon
        leading: Icon(const IconData(0xe800, fontFamily: 'PetinderIcon'), color: Colors.white),
        /// Title for appbar and style to make it white
        title: Text("Petinder",style: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.bold,)),
        actions: <Widget>[
          /// Login action button
//          IconButton(icon: const Icon(Icons.account_circle,color: Colors.white), onPressed: null), /// TODO Implement onPressed
          /// Create account action button
//          IconButton(icon: const Icon(Icons.person_add,color: Colors.white), onPressed: null), /// TODO Implement onPressed
        ],
      ),
      /// ********* Body ********* \\\
      /// Container to add padding and margin
      body: Container(
        margin: EdgeInsets.only(top: 10.0),
        padding: EdgeInsets.only(left: 30.0,right: 30.0),
        /// Main ListView to enable scrolling
        child: ListView(
          padding: EdgeInsets.all(15.0),
          children: <Widget>[
            /// Place Image on center
            Center(
              child: Image.asset('assets/images/ki85j78eT.png',),
            ),
            /// Login Getting
            Container(
              padding: EdgeInsets.only(top: 15.0, bottom: 15.0),
              child: Text("Register",
                textAlign: TextAlign.center,
                style: TextStyle(fontWeight: FontWeight.bold,),
              ),
            ),
            Column(
              // this Column will hold the EditTexts and Buttons
              children: <Widget>[
                ///////////////////////////////////////////////////
                ///////////// Email TextEdit with icon ////////////
                ///////////////////////////////////////////////////
                new EmailTextField(),
                //
                SizedBox(height: 10.0), // Add some margin
                //
                ///////////////////////////////////////////////////
                /////////// Password TextEdit with icon ///////////
                ///////////////////////////////////////////////////
                new PasswordField(),
                //
                SizedBox(height: 10.0), // Add some margin
                //
                new PasswordField(),

              ],

            )

          ],
        ),
      ),
    );
  }
}

// To use the icon go to http://fluttericon.com/
// Upload your icon
// Download the .zip file
// add the <fontName>.ttf file to fonts/<fontName>.ttf
// Add the .dart file into your lib/ (in this case i used lib/icon/)
// to use the icon now you can do Icon(const IconData(0xe800, fontFamily: 'PetinderIcon')
// the argument to Icon i got from the dart file generated by Flutter icon website